package com.kamtar.transport.api.enums;

public enum OperateurListeDeDroits {
	AFFICHAGE_CLIENTS,
	GESTION_CLIENTS,
	
	AFFICHAGE_TRANSPORTEURS,
	GESTION_TRANSPORTEURS,
	
	GESTION_OPERATIONS,
	AFFICHAGE_OPERATIONS,

	//GESTION_FACTURES_ENTRANTES,
	//GESTION_FACTURES_SORTANTES,
	
	AFFICHAGE_SMS,
	AFFICHAGE_EMAILS,
	AFFICHAGE_NOTIFICATIONS,
	
	GESTION_VEHICULE,
	AFFICHAGE_VEHICULE,
	
	GESTION_PROPRIETAIRE,
	AFFICHAGE_PROPRIETAIRE,

	CONSULTER_FACTURES_CLIENT,
	DECLENCHER_FACTURATION_CLIENT,

	CONSULTER_FACTURES_PROPRIETAIRE,
	DECLENCHER_FACTURATION_PROPRIETAIRE,

	SUPPRESSION_PROPRIETAIRE,
	SUPPRESSION_CLIENT,
	SUPPRESSION_DRIVER,
	SUPPRESSION_OPERATION,
	SUPPRESSION_VEHICULE,

	SUPPRESSION_FACTURATION_CLIENT,
	SUPPRESSION_FACTURATION_PROPRIETAIRE,

	CONSULTER_STATISTIQUES,

	GESTION_DEVIS,
	AFFICHAGE_DEVIS,

	GESTION_RECLAMATIONS
	
}
