package com.kamtar.transport.api.enums;

public enum OperationStatut {
	ENREGISTRE,
	EN_COURS_DE_TRAITEMENT,
	VALIDE,
	EN_ROUTE_VERS_CLIENT,
	ARRIVEE_CHEZ_CLIENT,
	CHARGEMENT_EN_COURS,
	CHARGEMENT_TERMINE,
	EN_DIRECTION_DESTINATION,
	ARRIVE_DESTINATION,
	DECHARGEMENT_EN_COURS,
	DECHARGEMENT_TERMINE
}

