package com.kamtar.transport.api.enums;

public enum TemplateEmail {
	ENVOYER_LIEN_MOT_DE_PASSE_PERDU_TRANSPORT,
	CONTACT_TRANSPORT,
	CONFIRMATION_COMMANDE_TRANSPORT,
	CONFIRMATION_CREATION_COMPTE,
	FIN_OPERATION,
	ENVOYER_FACTURE_CLIENT,

	NOUVEAU_COMPTE_CLIENT,
	NOUVELLE_COMMANDE_CLIENT,

	PROPOSER_PRIX_COMMANDE_TRANSPORT,
	NOUVELLE_DEMANDE_DEVIS_CLIENT,

	CONFIRMATION_COMMANDE_A_PARTIR_DE_DEVIS,
	NOUVEAU_DRIVER_CREE_PAR_PROPRIETAIRE,
	NOUVEAU_VEHICULE_CREE_PAR_PROPRIETAIRE,

	RAPPORT_JOURNALIER_OPERATIONS,
	RAPPORT_MENSUEL_OPERATIONS,

	NOUVELLE_RECLAMATION,
	NOUVELLE_RECLAMATION_CONFIRMATION,
	NOUVELLE_RECLAMATION_ECHANGE,
}
 