package com.kamtar.transport.api.enums;

public enum TemplateSMS {

	NOUVELLE_COMMANDE_POUR_TRANSPORTEUR_KAMTAR_TRANSPORT,
	NOUVELLE_DEMANDE_OPERATION,
	VALIDATION_COMPTE_CLIENT,
	NOUVELLE_COMMANDE_CLIENT,
	NOUVELLES_COMMANDES_CLIENT,
	NOUVEAU_DEVIS,
}
